/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DiscographyIndexRouteImport } from './routes/discography/index'
import { Route as DiscographySlugRouteImport } from './routes/discography/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscographyIndexRoute = DiscographyIndexRouteImport.update({
  id: '/discography/',
  path: '/discography/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscographySlugRoute = DiscographySlugRouteImport.update({
  id: '/discography/$slug',
  path: '/discography/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/discography/$slug': typeof DiscographySlugRoute
  '/discography/': typeof DiscographyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/discography/$slug': typeof DiscographySlugRoute
  '/discography': typeof DiscographyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/discography/$slug': typeof DiscographySlugRoute
  '/discography/': typeof DiscographyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/news' | '/profile' | '/discography/$slug' | '/discography/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/news' | '/profile' | '/discography/$slug' | '/discography'
  id:
    | '__root__'
    | '/'
    | '/news'
    | '/profile'
    | '/discography/$slug'
    | '/discography/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  DiscographySlugRoute: typeof DiscographySlugRoute
  DiscographyIndexRoute: typeof DiscographyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discography/': {
      id: '/discography/'
      path: '/discography'
      fullPath: '/discography/'
      preLoaderRoute: typeof DiscographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discography/$slug': {
      id: '/discography/$slug'
      path: '/discography/$slug'
      fullPath: '/discography/$slug'
      preLoaderRoute: typeof DiscographySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  DiscographySlugRoute: DiscographySlugRoute,
  DiscographyIndexRoute: DiscographyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
